#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.ActualInfo")]
	public partial class ActualInfo 	{

		#region Construction
		public ActualInfo()
		{
		}
		#endregion

		#region Column Mappings
		private int _Id;
		/// <summary>
		/// ID
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int Id
		{
			get { return _Id; }
			set {
				if (_Id != value) {
					_Id = value;
				}
			}
		}
		
		private string _ActualName;
		/// <summary>
		/// 现货名称
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string ActualName
		{
			get { return _ActualName; }
			set {
				if (_ActualName != value) {
					_ActualName = value;
				}
			}
		}
		
		private string _ActualCode;
		/// <summary>
		/// 现货代码
        /// </summary>
		[Column(DbType=@"VarChar(20)")]
		public string ActualCode
		{
			get { return _ActualCode; }
			set {
				if (_ActualCode != value) {
					_ActualCode = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591