#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.AdminMenuModule")]
	public partial class AdminMenuModule 	{

		#region Construction
		public AdminMenuModule()
		{
		}
		#endregion

		#region Column Mappings
		private int _ModuleId;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int ModuleId
		{
			get { return _ModuleId; }
			set {
				if (_ModuleId != value) {
					_ModuleId = value;
				}
			}
		}
		
		private int _ParentId;
		/// <summary>
		/// 0表示一级菜单，其余是二级菜单
        /// </summary>
		[Column(DbType=@"Int NOT NULL", CanBeNull=false)]
		public int ParentId
		{
			get { return _ParentId; }
			set {
				if (_ParentId != value) {
					_ParentId = value;
				}
			}
		}
		
		private string _ModuleName;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ModuleName
		{
			get { return _ModuleName; }
			set {
				if (_ModuleName != value) {
					_ModuleName = value;
				}
			}
		}
		
		private string _TargetUrl;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"NVarChar(255) NOT NULL", CanBeNull=false)]
		public string TargetUrl
		{
			get { return _TargetUrl; }
			set {
				if (_TargetUrl != value) {
					_TargetUrl = value;
				}
			}
		}
		
		private int _Status;
		/// <summary>
		/// 1显示，0不显示
        /// </summary>
		[Column(DbType=@"Int NOT NULL", CanBeNull=false)]
		public int Status
		{
			get { return _Status; }
			set {
				if (_Status != value) {
					_Status = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591