#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.Administrator")]
	public partial class Administrator 	{

		#region Construction
		public Administrator()
		{
		}
		#endregion

		#region Column Mappings
		private int _AdminId;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int AdminId
		{
			get { return _AdminId; }
			set {
				if (_AdminId != value) {
					_AdminId = value;
				}
			}
		}
		
		private string _AdminName;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"NVarChar(50) NOT NULL", CanBeNull=false)]
		public string AdminName
		{
			get { return _AdminName; }
			set {
				if (_AdminName != value) {
					_AdminName = value;
				}
			}
		}
		
		private int _Status;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int NOT NULL", CanBeNull=false)]
		public int Status
		{
			get { return _Status; }
			set {
				if (_Status != value) {
					_Status = value;
				}
			}
		}
		
		private string _Password;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"VarChar(50) NOT NULL", CanBeNull=false)]
		public string Password
		{
			get { return _Password; }
			set {
				if (_Password != value) {
					_Password = value;
				}
			}
		}
		
		private int _GroupId;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int NOT NULL", CanBeNull=false)]
		public int GroupId
		{
			get { return _GroupId; }
			set {
				if (_GroupId != value) {
					_GroupId = value;
				}
			}
		}
		
		private DateTime _LastLoginDate;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"DateTime NOT NULL", CanBeNull=false)]
		public DateTime LastLoginDate
		{
			get { return _LastLoginDate; }
			set {
				if (_LastLoginDate != value) {
					_LastLoginDate = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591