#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.AdminGroup")]
	public partial class AdminGroup 	{

		#region Construction
		public AdminGroup()
		{
		}
		#endregion

		#region Column Mappings
		private int _GroupId;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int GroupId
		{
			get { return _GroupId; }
			set {
				if (_GroupId != value) {
					_GroupId = value;
				}
			}
		}
		
		private string _GroupName;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"NVarChar(50) NOT NULL", CanBeNull=false)]
		public string GroupName
		{
			get { return _GroupName; }
			set {
				if (_GroupName != value) {
					_GroupName = value;
				}
			}
		}
		
		private string _Remark;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"NVarChar(50) NOT NULL", CanBeNull=false)]
		public string Remark
		{
			get { return _Remark; }
			set {
				if (_Remark != value) {
					_Remark = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591