#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.AnalystFans")]
	public partial class AnalystFans 	{

		#region Construction
		public AnalystFans()
		{
		}
		#endregion

		#region Column Mappings
		private int _Id;
		/// <summary>
		/// ID
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int Id
		{
			get { return _Id; }
			set {
				if (_Id != value) {
					_Id = value;
				}
			}
		}
		
		private int? _AnalystId;
		/// <summary>
		/// 分析师Id
        /// </summary>
		[Column(DbType=@"Int")]
		public int? AnalystId
		{
			get { return _AnalystId; }
			set {
				if (_AnalystId != value) {
					_AnalystId = value;
				}
			}
		}
		
		private string _AnalystName;
		/// <summary>
		/// 分析师名称
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string AnalystName
		{
			get { return _AnalystName; }
			set {
				if (_AnalystName != value) {
					_AnalystName = value;
				}
			}
		}
		
		private int? _CustomerId;
		/// <summary>
		/// 用户Id
        /// </summary>
		[Column(DbType=@"Int")]
		public int? CustomerId
		{
			get { return _CustomerId; }
			set {
				if (_CustomerId != value) {
					_CustomerId = value;
				}
			}
		}
		
		private string _CustomerName;
		/// <summary>
		/// 用户名
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string CustomerName
		{
			get { return _CustomerName; }
			set {
				if (_CustomerName != value) {
					_CustomerName = value;
				}
			}
		}
		
		private DateTime? _CreateTime;
		/// <summary>
		/// 关注时间
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? CreateTime
		{
			get { return _CreateTime; }
			set {
				if (_CreateTime != value) {
					_CreateTime = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591