#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.Analyst")]
	public partial class Analyst 	{

		#region Construction
		public Analyst()
		{
		}
		#endregion

		#region Column Mappings
		private int _AnalystId;
		/// <summary>
		/// 分析师Id
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int AnalystId
		{
			get { return _AnalystId; }
			set {
				if (_AnalystId != value) {
					_AnalystId = value;
				}
			}
		}
		
		private string _AnalystName;
		/// <summary>
		/// 分析师名
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string AnalystName
		{
			get { return _AnalystName; }
			set {
				if (_AnalystName != value) {
					_AnalystName = value;
				}
			}
		}
		
		private string _NickName;
		/// <summary>
		/// 别名
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string NickName
		{
			get { return _NickName; }
			set {
				if (_NickName != value) {
					_NickName = value;
				}
			}
		}
		
		private int? _FansNum;
		/// <summary>
		/// 粉丝数
        /// </summary>
		[Column(DbType=@"Int")]
		public int? FansNum
		{
			get { return _FansNum; }
			set {
				if (_FansNum != value) {
					_FansNum = value;
				}
			}
		}
		
		private string _Notice;
		/// <summary>
		/// 公告
        /// </summary>
		[Column(DbType=@"NVarChar(50)")]
		public string Notice
		{
			get { return _Notice; }
			set {
				if (_Notice != value) {
					_Notice = value;
				}
			}
		}
		
		private string _Intro;
		/// <summary>
		/// 简介
        /// </summary>
		[Column(DbType=@"NVarChar(100)")]
		public string Intro
		{
			get { return _Intro; }
			set {
				if (_Intro != value) {
					_Intro = value;
				}
			}
		}
		
		private string _ImgUrl;
		/// <summary>
		/// 头像图片url
        /// </summary>
		[Column(DbType=@"VarChar(200)")]
		public string ImgUrl
		{
			get { return _ImgUrl; }
			set {
				if (_ImgUrl != value) {
					_ImgUrl = value;
				}
			}
		}
		
		private int? _AdminId;
		/// <summary>
		/// 用户Id
        /// </summary>
		[Column(DbType=@"Int")]
		public int? AdminId
		{
			get { return _AdminId; }
			set {
				if (_AdminId != value) {
					_AdminId = value;
				}
			}
		}
		
		private int _AnalystType;
		/// <summary>
		/// 1：现货分析师，2：贵金属分析师
        /// </summary>
		[Column(DbType=@"Int NOT NULL", CanBeNull=false)]
		public int AnalystType
		{
			get { return _AnalystType; }
			set {
				if (_AnalystType != value) {
					_AnalystType = value;
				}
			}
		}
		
		private int? _VipType;
		/// <summary>
		/// 分析师类型
        /// </summary>
		[Column(DbType=@"Int")]
		public int? VipType
		{
			get { return _VipType; }
			set {
				if (_VipType != value) {
					_VipType = value;
				}
			}
		}
		
		private int _AnalystStatus;
		/// <summary>
		/// 1：可用,0：不可用
        /// </summary>
		[Column(DbType=@"Int NOT NULL", CanBeNull=false)]
		public int AnalystStatus
		{
			get { return _AnalystStatus; }
			set {
				if (_AnalystStatus != value) {
					_AnalystStatus = value;
				}
			}
		}
		
		private int? _SoftVersion;
		/// <summary>
		/// 软件版本
        /// </summary>
		[Column(DbType=@"Int")]
		public int? SoftVersion
		{
			get { return _SoftVersion; }
			set {
				if (_SoftVersion != value) {
					_SoftVersion = value;
				}
			}
		}
		
		private int? _Accuracy;
		/// <summary>
		/// 准确性
        /// </summary>
		[Column(DbType=@"Int")]
		public int? Accuracy
		{
			get { return _Accuracy; }
			set {
				if (_Accuracy != value) {
					_Accuracy = value;
				}
			}
		}
		
		private int? _Stability;
		/// <summary>
		/// 稳定性
        /// </summary>
		[Column(DbType=@"Int")]
		public int? Stability
		{
			get { return _Stability; }
			set {
				if (_Stability != value) {
					_Stability = value;
				}
			}
		}
		
		private int? _Defense;
		/// <summary>
		/// 防御力
        /// </summary>
		[Column(DbType=@"Int")]
		public int? Defense
		{
			get { return _Defense; }
			set {
				if (_Defense != value) {
					_Defense = value;
				}
			}
		}
		
		private int? _Attack;
		/// <summary>
		/// 攻击力
        /// </summary>
		[Column(DbType=@"Int")]
		public int? Attack
		{
			get { return _Attack; }
			set {
				if (_Attack != value) {
					_Attack = value;
				}
			}
		}
		
		private int? _Mentality;
		/// <summary>
		/// 心态
        /// </summary>
		[Column(DbType=@"Int")]
		public int? Mentality
		{
			get { return _Mentality; }
			set {
				if (_Mentality != value) {
					_Mentality = value;
				}
			}
		}
		
		private int? _AnalystSort;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int")]
		public int? AnalystSort
		{
			get { return _AnalystSort; }
			set {
				if (_AnalystSort != value) {
					_AnalystSort = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591