#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.AnalystLive")]
	public partial class AnalystLive 	{

		#region Construction
		public AnalystLive()
		{
		}
		#endregion

		#region Column Mappings
		private int _LiveId;
		/// <summary>
		/// 直播ID
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int LiveId
		{
			get { return _LiveId; }
			set {
				if (_LiveId != value) {
					_LiveId = value;
				}
			}
		}
		
		private int? _LiveType;
		/// <summary>
		/// 直播类型 一 1: 开仓; 2: 平仓; 3: 观点;
        /// </summary>
		[Column(DbType=@"Int")]
		public int? LiveType
		{
			get { return _LiveType; }
			set {
				if (_LiveType != value) {
					_LiveType = value;
				}
			}
		}
		
		private string _ActualName;
		/// <summary>
		/// 现货名称
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string ActualName
		{
			get { return _ActualName; }
			set {
				if (_ActualName != value) {
					_ActualName = value;
				}
			}
		}
		
		private string _ActualCode;
		/// <summary>
		/// 现货代码
        /// </summary>
		[Column(DbType=@"VarChar(20)")]
		public string ActualCode
		{
			get { return _ActualCode; }
			set {
				if (_ActualCode != value) {
					_ActualCode = value;
				}
			}
		}
		
		private decimal? _TransPrice;
		/// <summary>
		/// 交易价格
        /// </summary>
		[Column(DbType=@"Decimal(18,2)")]
		public decimal? TransPrice
		{
			get { return _TransPrice; }
			set {
				if (_TransPrice != value) {
					_TransPrice = value;
				}
			}
		}
		
		private string _TransType;
		/// <summary>
		/// 交易类型 一 开仓对应：买入订立, 卖出订立; 平仓对应：买入转让, 卖出转让;
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string TransType
		{
			get { return _TransType; }
			set {
				if (_TransType != value) {
					_TransType = value;
				}
			}
		}
		
		private decimal? _StopProfit;
		/// <summary>
		/// 止盈价格
        /// </summary>
		[Column(DbType=@"Decimal(18,2)")]
		public decimal? StopProfit
		{
			get { return _StopProfit; }
			set {
				if (_StopProfit != value) {
					_StopProfit = value;
				}
			}
		}
		
		private decimal? _StopLoss;
		/// <summary>
		/// 止损价格
        /// </summary>
		[Column(DbType=@"Decimal(18,2)")]
		public decimal? StopLoss
		{
			get { return _StopLoss; }
			set {
				if (_StopLoss != value) {
					_StopLoss = value;
				}
			}
		}
		
		private DateTime? _CreateTime;
		/// <summary>
		/// 创建时间
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? CreateTime
		{
			get { return _CreateTime; }
			set {
				if (_CreateTime != value) {
					_CreateTime = value;
				}
			}
		}
		
		private int? _AnalystId;
		/// <summary>
		/// 分析师Id
        /// </summary>
		[Column(DbType=@"Int")]
		public int? AnalystId
		{
			get { return _AnalystId; }
			set {
				if (_AnalystId != value) {
					_AnalystId = value;
				}
			}
		}
		
		private string _AnalystName;
		/// <summary>
		/// 分析师名称
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string AnalystName
		{
			get { return _AnalystName; }
			set {
				if (_AnalystName != value) {
					_AnalystName = value;
				}
			}
		}
		
		private string _Info;
		/// <summary>
		/// 直播信息
        /// </summary>
		[Column(DbType=@"VarChar(MAX)")]
		public string Info
		{
			get { return _Info; }
			set {
				if (_Info != value) {
					_Info = value;
				}
			}
		}
		
		private string _ImgUrl;
		/// <summary>
		/// 图片url, 多张图片用“,”隔开
        /// </summary>
		[Column(DbType=@"VarChar(300)")]
		public string ImgUrl
		{
			get { return _ImgUrl; }
			set {
				if (_ImgUrl != value) {
					_ImgUrl = value;
				}
			}
		}
		
		private string _LinkUrl;
		/// <summary>
		/// 超链接
        /// </summary>
		[Column(DbType=@"VarChar(300)")]
		public string LinkUrl
		{
			get { return _LinkUrl; }
			set {
				if (_LinkUrl != value) {
					_LinkUrl = value;
				}
			}
		}
		
		private int? _BuyLiveId;
		/// <summary>
		/// 平仓的时候, 对应的开仓Id, 一个平仓, 必须对应一条开仓记录
        /// </summary>
		[Column(DbType=@"Int")]
		public int? BuyLiveId
		{
			get { return _BuyLiveId; }
			set {
				if (_BuyLiveId != value) {
					_BuyLiveId = value;
				}
			}
		}
		
		private decimal? _ProfitRate;
		/// <summary>
		/// 盈利比例 , 平仓的时候计算这个值
        /// </summary>
		[Column(DbType=@"Decimal(18,4)")]
		public decimal? ProfitRate
		{
			get { return _ProfitRate; }
			set {
				if (_ProfitRate != value) {
					_ProfitRate = value;
				}
			}
		}
		
		private int? _IsSell;
		/// <summary>
		/// 0:未平仓 1:已平仓
        /// </summary>
		[Column(DbType=@"Int")]
		public int? IsSell
		{
			get { return _IsSell; }
			set {
				if (_IsSell != value) {
					_IsSell = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591