#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.AppDownload")]
	public partial class AppDownload 	{

		#region Construction
		public AppDownload()
		{
		}
		#endregion

		#region Column Mappings
		private int _Id;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int Id
		{
			get { return _Id; }
			set {
				if (_Id != value) {
					_Id = value;
				}
			}
		}
		
		private string _DeviceType;
		/// <summary>
		/// pc：手机，mobile：手机
        /// </summary>
		[Column(DbType=@"VarChar(10)")]
		public string DeviceType
		{
			get { return _DeviceType; }
			set {
				if (_DeviceType != value) {
					_DeviceType = value;
				}
			}
		}
		
		private string _SoftType;
		/// <summary>
		/// ios,android
        /// </summary>
		[Column(DbType=@"VarChar(10)")]
		public string SoftType
		{
			get { return _SoftType; }
			set {
				if (_SoftType != value) {
					_SoftType = value;
				}
			}
		}
		
		private int? _Num;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int")]
		public int? Num
		{
			get { return _Num; }
			set {
				if (_Num != value) {
					_Num = value;
				}
			}
		}
		
		private string _CreateTime;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"VarChar(20)")]
		public string CreateTime
		{
			get { return _CreateTime; }
			set {
				if (_CreateTime != value) {
					_CreateTime = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591