#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.AuthorityDotAdmin")]
	public partial class AuthorityDotAdmin 	{

		#region Construction
		public AuthorityDotAdmin()
		{
		}
		#endregion

		#region Column Mappings
		private int? _AuthorityDotId;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int")]
		public int? AuthorityDotId
		{
			get { return _AuthorityDotId; }
			set {
				if (_AuthorityDotId != value) {
					_AuthorityDotId = value;
				}
			}
		}
		
		private int? _AdminId;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int")]
		public int? AdminId
		{
			get { return _AdminId; }
			set {
				if (_AdminId != value) {
					_AdminId = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591