#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.AuthorityDot")]
	public partial class AuthorityDot 	{

		#region Construction
		public AuthorityDot()
		{
		}
		#endregion

		#region Column Mappings
		private int _Id;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int Id
		{
			get { return _Id; }
			set {
				if (_Id != value) {
					_Id = value;
				}
			}
		}
		
		private int? _ParentId;
		/// <summary>
		/// 父级Id, 0表示功能点
        /// </summary>
		[Column(DbType=@"Int")]
		public int? ParentId
		{
			get { return _ParentId; }
			set {
				if (_ParentId != value) {
					_ParentId = value;
				}
			}
		}
		
		private string _Text;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"NVarChar(50)")]
		public string Text
		{
			get { return _Text; }
			set {
				if (_Text != value) {
					_Text = value;
				}
			}
		}
		
		private int? _Type;
		/// <summary>
		/// 1:单选, 2:多选
        /// </summary>
		[Column(DbType=@"Int")]
		public int? Type
		{
			get { return _Type; }
			set {
				if (_Type != value) {
					_Type = value;
				}
			}
		}
		
		private string _RelevanceId;
		/// <summary>
		/// 关联Id
        /// </summary>
		[Column(DbType=@"NVarChar(50)")]
		public string RelevanceId
		{
			get { return _RelevanceId; }
			set {
				if (_RelevanceId != value) {
					_RelevanceId = value;
				}
			}
		}
		
		private bool? _Status;
		/// <summary>
		/// 状态, 是否可用
        /// </summary>
		[Column(DbType=@"Bit")]
		public bool? Status
		{
			get { return _Status; }
			set {
				if (_Status != value) {
					_Status = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591