#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.Calendar")]
	public partial class Calendar 	{

		#region Construction
		public Calendar()
		{
		}
		#endregion

		#region Column Mappings
		private int? _CId;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int")]
		public int? CId
		{
			get { return _CId; }
			set {
				if (_CId != value) {
					_CId = value;
				}
			}
		}
		
		private string _Country;
		/// <summary>
		/// 国家
        /// </summary>
		[Column(DbType=@"NVarChar(30)")]
		public string Country
		{
			get { return _Country; }
			set {
				if (_Country != value) {
					_Country = value;
				}
			}
		}
		
		private string _Title;
		/// <summary>
		/// 指标名称
        /// </summary>
		[Column(DbType=@"NVarChar(50)")]
		public string Title
		{
			get { return _Title; }
			set {
				if (_Title != value) {
					_Title = value;
				}
			}
		}
		
		private string _Important;
		/// <summary>
		/// 重要性
        /// </summary>
		[Column(DbType=@"NVarChar(10)")]
		public string Important
		{
			get { return _Important; }
			set {
				if (_Important != value) {
					_Important = value;
				}
			}
		}
		
		private string _FormerValue;
		/// <summary>
		/// 前值
        /// </summary>
		[Column(DbType=@"NVarChar(10)")]
		public string FormerValue
		{
			get { return _FormerValue; }
			set {
				if (_FormerValue != value) {
					_FormerValue = value;
				}
			}
		}
		
		private string _PredictedValues;
		/// <summary>
		/// 预测值
        /// </summary>
		[Column(DbType=@"NVarChar(10)")]
		public string PredictedValues
		{
			get { return _PredictedValues; }
			set {
				if (_PredictedValues != value) {
					_PredictedValues = value;
				}
			}
		}
		
		private string _PublishedValues;
		/// <summary>
		/// 公布值
        /// </summary>
		[Column(DbType=@"NVarChar(10)")]
		public string PublishedValues
		{
			get { return _PublishedValues; }
			set {
				if (_PublishedValues != value) {
					_PublishedValues = value;
				}
			}
		}
		
		private string _WavePoint;
		/// <summary>
		/// 波动点数
        /// </summary>
		[Column(DbType=@"NVarChar(10)")]
		public string WavePoint
		{
			get { return _WavePoint; }
			set {
				if (_WavePoint != value) {
					_WavePoint = value;
				}
			}
		}
		
		private string _Adress;
		/// <summary>
		/// 地址
        /// </summary>
		[Column(DbType=@"NVarChar(30)")]
		public string Adress
		{
			get { return _Adress; }
			set {
				if (_Adress != value) {
					_Adress = value;
				}
			}
		}
		
		private string _Events;
		/// <summary>
		/// 事件
        /// </summary>
		[Column(DbType=@"NVarChar(50)")]
		public string Events
		{
			get { return _Events; }
			set {
				if (_Events != value) {
					_Events = value;
				}
			}
		}
		
		private int? _SType;
		/// <summary>
		/// 1，经济数据 2财经大事，3假期提示
        /// </summary>
		[Column(DbType=@"Int")]
		public int? SType
		{
			get { return _SType; }
			set {
				if (_SType != value) {
					_SType = value;
				}
			}
		}
		
		private string _Remark;
		/// <summary>
		/// 备注
        /// </summary>
		[Column(DbType=@"NText")]
		public string Remark
		{
			get { return _Remark; }
			set {
				if (_Remark != value) {
					_Remark = value;
				}
			}
		}
		
		private DateTime? _CreateDate;
		/// <summary>
		/// 时间
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? CreateDate
		{
			get { return _CreateDate; }
			set {
				if (_CreateDate != value) {
					_CreateDate = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591