#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.Channel")]
	public partial class Channel 	{

		#region Construction
		public Channel()
		{
		}
		#endregion

		#region Column Mappings
		private string _ChannelId;
		/// <summary>
		/// 栏目ID
        /// </summary>
		[Column(DbType=@"VarChar(20) NOT NULL", IsPrimaryKey=true)]
		public string ChannelId
		{
			get { return _ChannelId; }
			set {
				if (_ChannelId != value) {
					_ChannelId = value;
				}
			}
		}
		
		private string _ParentId;
		/// <summary>
		/// 父节点ID 0：一级频频，其余存储父栏目的ChannelID
        /// </summary>
		[Column(DbType=@"VarChar(20) NOT NULL", CanBeNull=false)]
		public string ParentId
		{
			get { return _ParentId; }
			set {
				if (_ParentId != value) {
					_ParentId = value;
				}
			}
		}
		
		private string _ChannelName;
		/// <summary>
		/// 频道名称
        /// </summary>
		[Column(DbType=@"NVarChar(50) NOT NULL", CanBeNull=false)]
		public string ChannelName
		{
			get { return _ChannelName; }
			set {
				if (_ChannelName != value) {
					_ChannelName = value;
				}
			}
		}
		
		private string _Url;
		/// <summary>
		/// 频道首页地址
        /// </summary>
		[Column(DbType=@"VarChar(100)")]
		public string Url
		{
			get { return _Url; }
			set {
				if (_Url != value) {
					_Url = value;
				}
			}
		}
		
		private int _TypeId;
		/// <summary>
		/// 所属类型 1：普通栏目 2：碎片栏目
        /// </summary>
		[Column(DbType=@"Int NOT NULL", CanBeNull=false)]
		public int TypeId
		{
			get { return _TypeId; }
			set {
				if (_TypeId != value) {
					_TypeId = value;
				}
			}
		}
		
		private string _ChannelEnName;
		/// <summary>
		/// 频道英文名  程序判断唯一
        /// </summary>
		[Column(DbType=@"VarChar(20)")]
		public string ChannelEnName
		{
			get { return _ChannelEnName; }
			set {
				if (_ChannelEnName != value) {
					_ChannelEnName = value;
				}
			}
		}
		
		private string _CreateUser;
		/// <summary>
		/// 创建人
        /// </summary>
		[Column(DbType=@"VarChar(20) NOT NULL", CanBeNull=false)]
		public string CreateUser
		{
			get { return _CreateUser; }
			set {
				if (_CreateUser != value) {
					_CreateUser = value;
				}
			}
		}
		
		private DateTime _CreateTime;
		/// <summary>
		/// 创建时间
        /// </summary>
		[Column(DbType=@"DateTime NOT NULL", CanBeNull=false)]
		public DateTime CreateTime
		{
			get { return _CreateTime; }
			set {
				if (_CreateTime != value) {
					_CreateTime = value;
				}
			}
		}
		
		private string _UpdateUser;
		/// <summary>
		/// 修改人
        /// </summary>
		[Column(DbType=@"VarChar(20)")]
		public string UpdateUser
		{
			get { return _UpdateUser; }
			set {
				if (_UpdateUser != value) {
					_UpdateUser = value;
				}
			}
		}
		
		private DateTime? _UpdateTime;
		/// <summary>
		/// 修改时间
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? UpdateTime
		{
			get { return _UpdateTime; }
			set {
				if (_UpdateTime != value) {
					_UpdateTime = value;
				}
			}
		}
		
		private bool _Status;
		/// <summary>
		/// 状态 :true 可见,false不可见
        /// </summary>
		[Column(DbType=@"Bit NOT NULL", CanBeNull=false)]
		public bool Status
		{
			get { return _Status; }
			set {
				if (_Status != value) {
					_Status = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591