#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.CourseProgram")]
	public partial class CourseProgram 	{

		#region Construction
		public CourseProgram()
		{
		}
		#endregion

		#region Column Mappings
		private int _Id;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int Id
		{
			get { return _Id; }
			set {
				if (_Id != value) {
					_Id = value;
				}
			}
		}
		
		private string _CourseType;
		/// <summary>
		/// 课程类型
        /// </summary>
		[Column(DbType=@"NVarChar(50)")]
		public string CourseType
		{
			get { return _CourseType; }
			set {
				if (_CourseType != value) {
					_CourseType = value;
				}
			}
		}
		
		private string _ProgramTimeStart;
		/// <summary>
		/// 节目开始时间
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string ProgramTimeStart
		{
			get { return _ProgramTimeStart; }
			set {
				if (_ProgramTimeStart != value) {
					_ProgramTimeStart = value;
				}
			}
		}
		
		private string _ProgramTimeEnd;
		/// <summary>
		/// 节目结束时间
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string ProgramTimeEnd
		{
			get { return _ProgramTimeEnd; }
			set {
				if (_ProgramTimeEnd != value) {
					_ProgramTimeEnd = value;
				}
			}
		}
		
		private string _ProgramName;
		/// <summary>
		/// 节目名称
        /// </summary>
		[Column(DbType=@"NVarChar(50)")]
		public string ProgramName
		{
			get { return _ProgramName; }
			set {
				if (_ProgramName != value) {
					_ProgramName = value;
				}
			}
		}
		
		private string _ProgramUrl;
		/// <summary>
		/// 节目链接, 后改房号
        /// </summary>
		[Column(DbType=@"NVarChar(300)")]
		public string ProgramUrl
		{
			get { return _ProgramUrl; }
			set {
				if (_ProgramUrl != value) {
					_ProgramUrl = value;
				}
			}
		}
		
		private string _Property;
		/// <summary>
		/// 属性: 公开, 加密 等
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string Property
		{
			get { return _Property; }
			set {
				if (_Property != value) {
					_Property = value;
				}
			}
		}
		
		private int? _Weeks;
		/// <summary>
		/// 0: 星期天, 1: 星期一
        /// </summary>
		[Column(DbType=@"Int")]
		public int? Weeks
		{
			get { return _Weeks; }
			set {
				if (_Weeks != value) {
					_Weeks = value;
				}
			}
		}
		
		private string _SoftVersion;
		/// <summary>
		/// 软件版本
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string SoftVersion
		{
			get { return _SoftVersion; }
			set {
				if (_SoftVersion != value) {
					_SoftVersion = value;
				}
			}
		}
		
		private string _Editor;
		/// <summary>
		/// 编辑者
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string Editor
		{
			get { return _Editor; }
			set {
				if (_Editor != value) {
					_Editor = value;
				}
			}
		}
		
		private DateTime? _CreatedTime;
		/// <summary>
		/// 创建时间
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? CreatedTime
		{
			get { return _CreatedTime; }
			set {
				if (_CreatedTime != value) {
					_CreatedTime = value;
				}
			}
		}
		
		private int? _OrderNum;
		/// <summary>
		/// 排序优先级, 数值越大, 优先级越小
        /// </summary>
		[Column(DbType=@"Int")]
		public int? OrderNum
		{
			get { return _OrderNum; }
			set {
				if (_OrderNum != value) {
					_OrderNum = value;
				}
			}
		}
		
		private int? _Status;
		/// <summary>
		/// 状态, 0:休息, 1:开课
        /// </summary>
		[Column(DbType=@"Int")]
		public int? Status
		{
			get { return _Status; }
			set {
				if (_Status != value) {
					_Status = value;
				}
			}
		}
		
		private int? _PassageType;
		/// <summary>
		/// 通道类型, 0: 正常打开, 1: CRM通道
        /// </summary>
		[Column(DbType=@"Int")]
		public int? PassageType
		{
			get { return _PassageType; }
			set {
				if (_PassageType != value) {
					_PassageType = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591