#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.CourseRecommend")]
	public partial class CourseRecommend 	{

		#region Construction
		public CourseRecommend()
		{
		}
		#endregion

		#region Column Mappings
		private int _Id;
		/// <summary>
		/// Id
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int Id
		{
			get { return _Id; }
			set {
				if (_Id != value) {
					_Id = value;
				}
			}
		}
		
		private string _Title;
		/// <summary>
		/// 标题
        /// </summary>
		[Column(DbType=@"NVarChar(50)")]
		public string Title
		{
			get { return _Title; }
			set {
				if (_Title != value) {
					_Title = value;
				}
			}
		}
		
		private string _Introduction;
		/// <summary>
		/// 简介
        /// </summary>
		[Column(DbType=@"NVarChar(500)")]
		public string Introduction
		{
			get { return _Introduction; }
			set {
				if (_Introduction != value) {
					_Introduction = value;
				}
			}
		}
		
		private string _DateStart;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string DateStart
		{
			get { return _DateStart; }
			set {
				if (_DateStart != value) {
					_DateStart = value;
				}
			}
		}
		
		private string _DateTimeStart;
		/// <summary>
		/// 开始时间
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string DateTimeStart
		{
			get { return _DateTimeStart; }
			set {
				if (_DateTimeStart != value) {
					_DateTimeStart = value;
				}
			}
		}
		
		private string _DateTimeEnd;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string DateTimeEnd
		{
			get { return _DateTimeEnd; }
			set {
				if (_DateTimeEnd != value) {
					_DateTimeEnd = value;
				}
			}
		}
		
		private string _RoomId;
		/// <summary>
		/// 房号
        /// </summary>
		[Column(DbType=@"NVarChar(50)")]
		public string RoomId
		{
			get { return _RoomId; }
			set {
				if (_RoomId != value) {
					_RoomId = value;
				}
			}
		}
		
		private string _SoftVersion;
		/// <summary>
		/// 软件版本
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string SoftVersion
		{
			get { return _SoftVersion; }
			set {
				if (_SoftVersion != value) {
					_SoftVersion = value;
				}
			}
		}
		
		private int? _Status;
		/// <summary>
		/// 状态, 0:不推荐, 1:推荐
        /// </summary>
		[Column(DbType=@"Int")]
		public int? Status
		{
			get { return _Status; }
			set {
				if (_Status != value) {
					_Status = value;
				}
			}
		}
		
		private string _Editor;
		/// <summary>
		/// 编辑者
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string Editor
		{
			get { return _Editor; }
			set {
				if (_Editor != value) {
					_Editor = value;
				}
			}
		}
		
		private DateTime? _EditTime;
		/// <summary>
		/// 编辑时间
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? EditTime
		{
			get { return _EditTime; }
			set {
				if (_EditTime != value) {
					_EditTime = value;
				}
			}
		}
		
		private int? _PassageType;
		/// <summary>
		/// 通道类型, 0: 正常打开, 1: CRM通道
        /// </summary>
		[Column(DbType=@"Int")]
		public int? PassageType
		{
			get { return _PassageType; }
			set {
				if (_PassageType != value) {
					_PassageType = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591