#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.CustomerGroup")]
	public partial class CustomerGroup 	{

		#region Construction
		public CustomerGroup()
		{
		}
		#endregion

		#region Column Mappings
		private int _Id;
		/// <summary>
		/// ID
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int Id
		{
			get { return _Id; }
			set {
				if (_Id != value) {
					_Id = value;
				}
			}
		}
		
		private string _GroupName;
		/// <summary>
		/// 组名称
        /// </summary>
		[Column(DbType=@"NVarChar(50)")]
		public string GroupName
		{
			get { return _GroupName; }
			set {
				if (_GroupName != value) {
					_GroupName = value;
				}
			}
		}
		
		private int? _CustomerId;
		/// <summary>
		/// 用户Id
        /// </summary>
		[Column(DbType=@"Int")]
		public int? CustomerId
		{
			get { return _CustomerId; }
			set {
				if (_CustomerId != value) {
					_CustomerId = value;
				}
			}
		}
		
		private string _CustomerName;
		/// <summary>
		/// 用户名
        /// </summary>
		[Column(DbType=@"NVarChar(50)")]
		public string CustomerName
		{
			get { return _CustomerName; }
			set {
				if (_CustomerName != value) {
					_CustomerName = value;
				}
			}
		}
		
		private int? _GroupType;
		/// <summary>
		/// 组类型, 1：自己上传, 2：CRM
        /// </summary>
		[Column(DbType=@"Int")]
		public int? GroupType
		{
			get { return _GroupType; }
			set {
				if (_GroupType != value) {
					_GroupType = value;
				}
			}
		}
		
		private string _Editor;
		/// <summary>
		/// 操作人
        /// </summary>
		[Column(DbType=@"NChar(20)")]
		public string Editor
		{
			get { return _Editor; }
			set {
				if (_Editor != value) {
					_Editor = value;
				}
			}
		}
		
		private DateTime? _CreatedTime;
		/// <summary>
		/// 操作时间
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? CreatedTime
		{
			get { return _CreatedTime; }
			set {
				if (_CreatedTime != value) {
					_CreatedTime = value;
				}
			}
		}
		
		private string _RelevanceId;
		/// <summary>
		/// 投放版本ID
        /// </summary>
		[Column(DbType=@"NVarChar(50)")]
		public string RelevanceId
		{
			get { return _RelevanceId; }
			set {
				if (_RelevanceId != value) {
					_RelevanceId = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591