#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.Direction")]
	public partial class Direction 	{

		#region Construction
		public Direction()
		{
		}
		#endregion

		#region Column Mappings
		private int _Id;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int Id
		{
			get { return _Id; }
			set {
				if (_Id != value) {
					_Id = value;
				}
			}
		}
		
		private int? _TypeId;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int")]
		public int? TypeId
		{
			get { return _TypeId; }
			set {
				if (_TypeId != value) {
					_TypeId = value;
				}
			}
		}
		
		private string _MarketQuotations;
		/// <summary>
		/// 市场行情
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string MarketQuotations
		{
			get { return _MarketQuotations; }
			set {
				if (_MarketQuotations != value) {
					_MarketQuotations = value;
				}
			}
		}
		
		private string _Popularity;
		/// <summary>
		/// 人气指标
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string Popularity
		{
			get { return _Popularity; }
			set {
				if (_Popularity != value) {
					_Popularity = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591