#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.Fragment")]
	public partial class Fragment 	{

		#region Construction
		public Fragment()
		{
		}
		#endregion

		#region Column Mappings
		private int _FragmentId;
		/// <summary>
		/// 编号
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int FragmentId
		{
			get { return _FragmentId; }
			set {
				if (_FragmentId != value) {
					_FragmentId = value;
				}
			}
		}
		
		private string _ChannelId;
		/// <summary>
		/// 栏目ID
        /// </summary>
		[Column(DbType=@"NVarChar(20) NOT NULL", CanBeNull=false)]
		public string ChannelId
		{
			get { return _ChannelId; }
			set {
				if (_ChannelId != value) {
					_ChannelId = value;
				}
			}
		}
		
		private int? _TypeId;
		/// <summary>
		/// 碎片类型0:首页碎片1:列表页碎片2:文章页碎片
        /// </summary>
		[Column(DbType=@"Int")]
		public int? TypeId
		{
			get { return _TypeId; }
			set {
				if (_TypeId != value) {
					_TypeId = value;
				}
			}
		}
		
		private string _Content;
		/// <summary>
		/// 碎片内容
        /// </summary>
		[Column(DbType=@"NVarChar(MAX)")]
		public string Content
		{
			get { return _Content; }
			set {
				if (_Content != value) {
					_Content = value;
				}
			}
		}
		
		private int? _OrderNum;
		/// <summary>
		/// 排序号
        /// </summary>
		[Column(DbType=@"Int")]
		public int? OrderNum
		{
			get { return _OrderNum; }
			set {
				if (_OrderNum != value) {
					_OrderNum = value;
				}
			}
		}
		
		private string _CreatedUser;
		/// <summary>
		/// 推荐人
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string CreatedUser
		{
			get { return _CreatedUser; }
			set {
				if (_CreatedUser != value) {
					_CreatedUser = value;
				}
			}
		}
		
		private DateTime? _CreatedTime;
		/// <summary>
		/// 推荐日期
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? CreatedTime
		{
			get { return _CreatedTime; }
			set {
				if (_CreatedTime != value) {
					_CreatedTime = value;
				}
			}
		}
		
		private string _UpdatedUser;
		/// <summary>
		/// 更新用户
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string UpdatedUser
		{
			get { return _UpdatedUser; }
			set {
				if (_UpdatedUser != value) {
					_UpdatedUser = value;
				}
			}
		}
		
		private DateTime? _UpdatedTime;
		/// <summary>
		/// 更新时间
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? UpdatedTime
		{
			get { return _UpdatedTime; }
			set {
				if (_UpdatedTime != value) {
					_UpdatedTime = value;
				}
			}
		}
		
		private string _DeletedUser;
		/// <summary>
		/// 删除用户
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string DeletedUser
		{
			get { return _DeletedUser; }
			set {
				if (_DeletedUser != value) {
					_DeletedUser = value;
				}
			}
		}
		
		private DateTime? _DeletedTime;
		/// <summary>
		/// 删除时间
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? DeletedTime
		{
			get { return _DeletedTime; }
			set {
				if (_DeletedTime != value) {
					_DeletedTime = value;
				}
			}
		}
		
		private bool? _IsDeleted;
		/// <summary>
		/// 是否删除
        /// </summary>
		[Column(DbType=@"Bit")]
		public bool? IsDeleted
		{
			get { return _IsDeleted; }
			set {
				if (_IsDeleted != value) {
					_IsDeleted = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591