#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.Functions")]
	public partial class Functions 	{

		#region Construction
		public Functions()
		{
		}
		#endregion

		#region Column Mappings
		private int _FunctionId;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int NOT NULL", CanBeNull=false)]
		public int FunctionId
		{
			get { return _FunctionId; }
			set {
				if (_FunctionId != value) {
					_FunctionId = value;
				}
			}
		}
		
		private string _FunctionName;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"NVarChar(10) NOT NULL", CanBeNull=false)]
		public string FunctionName
		{
			get { return _FunctionName; }
			set {
				if (_FunctionName != value) {
					_FunctionName = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591