#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.InformationOfUser")]
	public partial class InformationOfUser 	{

		#region Construction
		public InformationOfUser()
		{
		}
		#endregion

		#region Column Mappings
		private int _Id;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int Id
		{
			get { return _Id; }
			set {
				if (_Id != value) {
					_Id = value;
				}
			}
		}
		
		private int? _ReceiverId;
		/// <summary>
		/// 接收者Id
        /// </summary>
		[Column(DbType=@"Int")]
		public int? ReceiverId
		{
			get { return _ReceiverId; }
			set {
				if (_ReceiverId != value) {
					_ReceiverId = value;
				}
			}
		}
		
		private string _Receiver;
		/// <summary>
		/// 用户,接收者
        /// </summary>
		[Column(DbType=@"NVarChar(20) NOT NULL", CanBeNull=false)]
		public string Receiver
		{
			get { return _Receiver; }
			set {
				if (_Receiver != value) {
					_Receiver = value;
				}
			}
		}
		
		private int _NewsId;
		/// <summary>
		/// 资讯Id
        /// </summary>
		[Column(DbType=@"Int NOT NULL", CanBeNull=false)]
		public int NewsId
		{
			get { return _NewsId; }
			set {
				if (_NewsId != value) {
					_NewsId = value;
				}
			}
		}
		
		private int? _ParentId;
		/// <summary>
		/// 弹窗Id,自表:PopupMsgPlan
        /// </summary>
		[Column(DbType=@"Int")]
		public int? ParentId
		{
			get { return _ParentId; }
			set {
				if (_ParentId != value) {
					_ParentId = value;
				}
			}
		}
		
		private int? _PushColumn;
		/// <summary>
		/// 推送栏目, 1: 公告, 2: 解盘
        /// </summary>
		[Column(DbType=@"Int")]
		public int? PushColumn
		{
			get { return _PushColumn; }
			set {
				if (_PushColumn != value) {
					_PushColumn = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591