#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.MediaClass")]
	public partial class MediaClass 	{

		#region Construction
		public MediaClass()
		{
		}
		#endregion

		#region Column Mappings
		private int _MediaClassId;
		/// <summary>
		/// 文件类别ID
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int MediaClassId
		{
			get { return _MediaClassId; }
			set {
				if (_MediaClassId != value) {
					_MediaClassId = value;
				}
			}
		}
		
		private string _MediaClassName;
		/// <summary>
		/// 文件类别名
        /// </summary>
		[Column(DbType=@"NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MediaClassName
		{
			get { return _MediaClassName; }
			set {
				if (_MediaClassName != value) {
					_MediaClassName = value;
				}
			}
		}
		
		private int _SortId;
		/// <summary>
		/// 排序号
        /// </summary>
		[Column(DbType=@"Int NOT NULL", CanBeNull=false)]
		public int SortId
		{
			get { return _SortId; }
			set {
				if (_SortId != value) {
					_SortId = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591