#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.Media")]
	public partial class Media 	{

		#region Construction
		public Media()
		{
		}
		#endregion

		#region Column Mappings
		private int _MediaId;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int MediaId
		{
			get { return _MediaId; }
			set {
				if (_MediaId != value) {
					_MediaId = value;
				}
			}
		}
		
		private int _MediaClassId;
		/// <summary>
		/// 文件类别ID
        /// </summary>
		[Column(DbType=@"Int NOT NULL", CanBeNull=false)]
		public int MediaClassId
		{
			get { return _MediaClassId; }
			set {
				if (_MediaClassId != value) {
					_MediaClassId = value;
				}
			}
		}
		
		private string _MediaTitle;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"VarChar(100)")]
		public string MediaTitle
		{
			get { return _MediaTitle; }
			set {
				if (_MediaTitle != value) {
					_MediaTitle = value;
				}
			}
		}
		
		private DateTime _UploadTime;
		/// <summary>
		/// 上传时间
        /// </summary>
		[Column(DbType=@"DateTime NOT NULL", CanBeNull=false)]
		public DateTime UploadTime
		{
			get { return _UploadTime; }
			set {
				if (_UploadTime != value) {
					_UploadTime = value;
				}
			}
		}
		
		private string _UploadPath;
		/// <summary>
		/// 文件上传路径
        /// </summary>
		[Column(DbType=@"VarChar(255) NOT NULL", CanBeNull=false)]
		public string UploadPath
		{
			get { return _UploadPath; }
			set {
				if (_UploadPath != value) {
					_UploadPath = value;
				}
			}
		}
		
		private long _MediaSize;
		/// <summary>
		/// 文件大小
        /// </summary>
		[Column(DbType=@"BigInt NOT NULL", CanBeNull=false)]
		public long MediaSize
		{
			get { return _MediaSize; }
			set {
				if (_MediaSize != value) {
					_MediaSize = value;
				}
			}
		}
		
		private int? _MediaType;
		/// <summary>
		/// 文件类型
        /// </summary>
		[Column(DbType=@"Int")]
		public int? MediaType
		{
			get { return _MediaType; }
			set {
				if (_MediaType != value) {
					_MediaType = value;
				}
			}
		}
		
		private string _Uploader;
		/// <summary>
		/// 上传人
        /// </summary>
		[Column(DbType=@"VarChar(50) NOT NULL", CanBeNull=false)]
		public string Uploader
		{
			get { return _Uploader; }
			set {
				if (_Uploader != value) {
					_Uploader = value;
				}
			}
		}
		
		private string _MediaLabel;
		/// <summary>
		/// 文件标签
        /// </summary>
		[Column(DbType=@"VarChar(100)")]
		public string MediaLabel
		{
			get { return _MediaLabel; }
			set {
				if (_MediaLabel != value) {
					_MediaLabel = value;
				}
			}
		}
		
		private string _MediaDescript;
		/// <summary>
		/// 文件说明
        /// </summary>
		[Column(DbType=@"VarChar(500)")]
		public string MediaDescript
		{
			get { return _MediaDescript; }
			set {
				if (_MediaDescript != value) {
					_MediaDescript = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591