#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.NewsPopup")]
	public partial class NewsPopup 	{

		#region Construction
		public NewsPopup()
		{
		}
		#endregion

		#region Column Mappings
		private int _Id;
		/// <summary>
		/// ID
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int Id
		{
			get { return _Id; }
			set {
				if (_Id != value) {
					_Id = value;
				}
			}
		}
		
		private int? _NewsId;
		/// <summary>
		/// 资讯Id
        /// </summary>
		[Column(DbType=@"Int")]
		public int? NewsId
		{
			get { return _NewsId; }
			set {
				if (_NewsId != value) {
					_NewsId = value;
				}
			}
		}
		
		private string _Title;
		/// <summary>
		/// 标题
        /// </summary>
		[Column(DbType=@"NVarChar(30)")]
		public string Title
		{
			get { return _Title; }
			set {
				if (_Title != value) {
					_Title = value;
				}
			}
		}
		
		private string _Author;
		/// <summary>
		/// 作者
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string Author
		{
			get { return _Author; }
			set {
				if (_Author != value) {
					_Author = value;
				}
			}
		}
		
		private DateTime? _CreatedTime;
		/// <summary>
		/// 创建时间
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? CreatedTime
		{
			get { return _CreatedTime; }
			set {
				if (_CreatedTime != value) {
					_CreatedTime = value;
				}
			}
		}
		
		private string _PushColumn;
		/// <summary>
		/// 推送栏目
        /// </summary>
		[Column(DbType=@"NVarChar(50)")]
		public string PushColumn
		{
			get { return _PushColumn; }
			set {
				if (_PushColumn != value) {
					_PushColumn = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591