#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.NewsTitlePrefix")]
	public partial class NewsTitlePrefix 	{

		#region Construction
		public NewsTitlePrefix()
		{
		}
		#endregion

		#region Column Mappings
		private int _Id;
		/// <summary>
		/// Id
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int Id
		{
			get { return _Id; }
			set {
				if (_Id != value) {
					_Id = value;
				}
			}
		}
		
		private string _Prefix;
		/// <summary>
		/// 标题前标签
        /// </summary>
		[Column(DbType=@"NVarChar(50)")]
		public string Prefix
		{
			get { return _Prefix; }
			set {
				if (_Prefix != value) {
					_Prefix = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591