#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.NewsAppraisal")]
	public partial class NewsAppraisal 	{

		#region Construction
		public NewsAppraisal()
		{
		}
		#endregion

		#region Column Mappings
		private string _NewsId;
		/// <summary>
		/// 资讯Id
        /// </summary>
		[Column(DbType=@"VarChar(20)")]
		public string NewsId
		{
			get { return _NewsId; }
			set {
				if (_NewsId != value) {
					_NewsId = value;
				}
			}
		}
		
		private int? _Option1;
		/// <summary>
		/// 选项1, 顶
        /// </summary>
		[Column(DbType=@"Int")]
		public int? Option1
		{
			get { return _Option1; }
			set {
				if (_Option1 != value) {
					_Option1 = value;
				}
			}
		}
		
		private int? _Option2;
		/// <summary>
		/// 选项2, 踩
        /// </summary>
		[Column(DbType=@"Int")]
		public int? Option2
		{
			get { return _Option2; }
			set {
				if (_Option2 != value) {
					_Option2 = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591