#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.NewsStockRelation")]
	public partial class NewsStockRelation 	{

		#region Construction
		public NewsStockRelation()
		{
		}
		#endregion

		#region Column Mappings
		private string _Id;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"NChar(10)")]
		public string Id
		{
			get { return _Id; }
			set {
				if (_Id != value) {
					_Id = value;
				}
			}
		}
		
		private int? _NewsId;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int")]
		public int? NewsId
		{
			get { return _NewsId; }
			set {
				if (_NewsId != value) {
					_NewsId = value;
				}
			}
		}
		
		private string _StockCode;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"NVarChar(10)")]
		public string StockCode
		{
			get { return _StockCode; }
			set {
				if (_StockCode != value) {
					_StockCode = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591