#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.News")]
	public partial class News 	{

		#region Construction
		public News()
		{
		}
		#endregion

		#region Column Mappings
		private int _NewsId;
		/// <summary>
		/// 编号
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int NewsId
		{
			get { return _NewsId; }
			set {
				if (_NewsId != value) {
					_NewsId = value;
				}
			}
		}
		
		private string _ChannelId;
		/// <summary>
		/// 栏目ID
        /// </summary>
		[Column(DbType=@"VarChar(20) NOT NULL", CanBeNull=false)]
		public string ChannelId
		{
			get { return _ChannelId; }
			set {
				if (_ChannelId != value) {
					_ChannelId = value;
				}
			}
		}
		
		private string _Title;
		/// <summary>
		/// 文章标题
        /// </summary>
		[Column(DbType=@"NVarChar(200) NOT NULL", CanBeNull=false)]
		public string Title
		{
			get { return _Title; }
			set {
				if (_Title != value) {
					_Title = value;
				}
			}
		}
		
		private string _Author;
		/// <summary>
		/// 作者
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string Author
		{
			get { return _Author; }
			set {
				if (_Author != value) {
					_Author = value;
				}
			}
		}
		
		private string _KeyWord;
		/// <summary>
		/// 关键字
        /// </summary>
		[Column(DbType=@"NVarChar(50)")]
		public string KeyWord
		{
			get { return _KeyWord; }
			set {
				if (_KeyWord != value) {
					_KeyWord = value;
				}
			}
		}
		
		private string _NewsAbstract;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"NVarChar(200)")]
		public string NewsAbstract
		{
			get { return _NewsAbstract; }
			set {
				if (_NewsAbstract != value) {
					_NewsAbstract = value;
				}
			}
		}
		
		private string _OrderDay;
		/// <summary>
		/// 排序日期yyyyMMdd
        /// </summary>
		[Column(DbType=@"VarChar(8)")]
		public string OrderDay
		{
			get { return _OrderDay; }
			set {
				if (_OrderDay != value) {
					_OrderDay = value;
				}
			}
		}
		
		private string _OrderTime;
		/// <summary>
		/// 排序时间hh:mm:ss
        /// </summary>
		[Column(DbType=@"VarChar(8)")]
		public string OrderTime
		{
			get { return _OrderTime; }
			set {
				if (_OrderTime != value) {
					_OrderTime = value;
				}
			}
		}
		
		private int? _OrderNum;
		/// <summary>
		/// 权重
        /// </summary>
		[Column(DbType=@"Int")]
		public int? OrderNum
		{
			get { return _OrderNum; }
			set {
				if (_OrderNum != value) {
					_OrderNum = value;
				}
			}
		}
		
		private string _Url;
		/// <summary>
		/// 自定义URL
        /// </summary>
		[Column(DbType=@"VarChar(400)")]
		public string Url
		{
			get { return _Url; }
			set {
				if (_Url != value) {
					_Url = value;
				}
			}
		}
		
		private int _Sort;
		/// <summary>
		/// 类型：0-图片文章,1-新文章,2-空文章,3-文件下载
        /// </summary>
		[Column(DbType=@"Int NOT NULL", CanBeNull=false)]
		public int Sort
		{
			get { return _Sort; }
			set {
				if (_Sort != value) {
					_Sort = value;
				}
			}
		}
		
		private int? _Status;
		/// <summary>
		/// 文章状态：0-待审,-1-拒绝，1-公开
        /// </summary>
		[Column(DbType=@"Int")]
		public int? Status
		{
			get { return _Status; }
			set {
				if (_Status != value) {
					_Status = value;
				}
			}
		}
		
		private string _CreatedUser;
		/// <summary>
		/// 责任编辑
        /// </summary>
		[Column(DbType=@"NVarChar(10)")]
		public string CreatedUser
		{
			get { return _CreatedUser; }
			set {
				if (_CreatedUser != value) {
					_CreatedUser = value;
				}
			}
		}
		
		private DateTime? _CreatedTime;
		/// <summary>
		/// 创建时间
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? CreatedTime
		{
			get { return _CreatedTime; }
			set {
				if (_CreatedTime != value) {
					_CreatedTime = value;
				}
			}
		}
		
		private string _UpdatedUser;
		/// <summary>
		/// 更新用户
        /// </summary>
		[Column(DbType=@"NVarChar(10)")]
		public string UpdatedUser
		{
			get { return _UpdatedUser; }
			set {
				if (_UpdatedUser != value) {
					_UpdatedUser = value;
				}
			}
		}
		
		private DateTime? _UpdatedTime;
		/// <summary>
		/// 更新时间
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? UpdatedTime
		{
			get { return _UpdatedTime; }
			set {
				if (_UpdatedTime != value) {
					_UpdatedTime = value;
				}
			}
		}
		
		private string _SecondTitle;
		/// <summary>
		/// 二级标题,多个主题之间用[WL]隔开
        /// </summary>
		[Column(DbType=@"NVarChar(200)")]
		public string SecondTitle
		{
			get { return _SecondTitle; }
			set {
				if (_SecondTitle != value) {
					_SecondTitle = value;
				}
			}
		}
		
		private string _SecondUrl;
		/// <summary>
		/// 二级超链接地址,多个链接之间用[WL]隔开
        /// </summary>
		[Column(DbType=@"VarChar(500)")]
		public string SecondUrl
		{
			get { return _SecondUrl; }
			set {
				if (_SecondUrl != value) {
					_SecondUrl = value;
				}
			}
		}
		
		private string _TitleColor;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"VarChar(50)")]
		public string TitleColor
		{
			get { return _TitleColor; }
			set {
				if (_TitleColor != value) {
					_TitleColor = value;
				}
			}
		}
		
		private string _IsBold;
		/// <summary>
		/// 是否粗体：0-否,1-是,多个值之间用[WL]隔开
        /// </summary>
		[Column(DbType=@"VarChar(50)")]
		public string IsBold
		{
			get { return _IsBold; }
			set {
				if (_IsBold != value) {
					_IsBold = value;
				}
			}
		}
		
		private string _ImgUrl;
		/// <summary>
		/// 图片新闻的图片路径
        /// </summary>
		[Column(DbType=@"VarChar(100)")]
		public string ImgUrl
		{
			get { return _ImgUrl; }
			set {
				if (_ImgUrl != value) {
					_ImgUrl = value;
				}
			}
		}
		
		private string _FileUrl;
		/// <summary>
		/// 下载文件路径
        /// </summary>
		[Column(DbType=@"VarChar(100)")]
		public string FileUrl
		{
			get { return _FileUrl; }
			set {
				if (_FileUrl != value) {
					_FileUrl = value;
				}
			}
		}
		
		private int? _ParentNewsId;
		/// <summary>
		/// 所属新闻ID
        /// </summary>
		[Column(DbType=@"Int")]
		public int? ParentNewsId
		{
			get { return _ParentNewsId; }
			set {
				if (_ParentNewsId != value) {
					_ParentNewsId = value;
				}
			}
		}
		
		private bool? _IsRetinue;
		/// <summary>
		/// 是否所属文章
        /// </summary>
		[Column(DbType=@"Bit")]
		public bool? IsRetinue
		{
			get { return _IsRetinue; }
			set {
				if (_IsRetinue != value) {
					_IsRetinue = value;
				}
			}
		}
		
		private string _Prefix;
		/// <summary>
		/// 标题前标签
        /// </summary>
		[Column(DbType=@"NVarChar(50)")]
		public string Prefix
		{
			get { return _Prefix; }
			set {
				if (_Prefix != value) {
					_Prefix = value;
				}
			}
		}
		
		private string _StockCode;
		/// <summary>
		/// 股票ID
        /// </summary>
		[Column(DbType=@"VarChar(200)")]
		public string StockCode
		{
			get { return _StockCode; }
			set {
				if (_StockCode != value) {
					_StockCode = value;
				}
			}
		}
		
		private int? _Important;
		/// <summary>
		/// 重要性
        /// </summary>
		[Column(DbType=@"Int")]
		public int? Important
		{
			get { return _Important; }
			set {
				if (_Important != value) {
					_Important = value;
				}
			}
		}
		
		private int? _Reliability;
		/// <summary>
		/// 可信度
        /// </summary>
		[Column(DbType=@"Int")]
		public int? Reliability
		{
			get { return _Reliability; }
			set {
				if (_Reliability != value) {
					_Reliability = value;
				}
			}
		}
		
		private int? _Effect;
		/// <summary>
		/// 影响力
        /// </summary>
		[Column(DbType=@"Int")]
		public int? Effect
		{
			get { return _Effect; }
			set {
				if (_Effect != value) {
					_Effect = value;
				}
			}
		}
		
		private DateTime? _DeadLine;
		/// <summary>
		/// 截止时间
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? DeadLine
		{
			get { return _DeadLine; }
			set {
				if (_DeadLine != value) {
					_DeadLine = value;
				}
			}
		}
		
		private string _LastValue;
		/// <summary>
		/// 前值
        /// </summary>
		[Column(DbType=@"VarChar(10)")]
		public string LastValue
		{
			get { return _LastValue; }
			set {
				if (_LastValue != value) {
					_LastValue = value;
				}
			}
		}
		
		private string _ForeCast;
		/// <summary>
		/// 预测值
        /// </summary>
		[Column(DbType=@"VarChar(100)")]
		public string ForeCast
		{
			get { return _ForeCast; }
			set {
				if (_ForeCast != value) {
					_ForeCast = value;
				}
			}
		}
		
		private string _HUrl;
		/// <summary>
		/// 历史分析地址
        /// </summary>
		[Column(DbType=@"VarChar(100)")]
		public string HUrl
		{
			get { return _HUrl; }
			set {
				if (_HUrl != value) {
					_HUrl = value;
				}
			}
		}
		
		private string _CUrl;
		/// <summary>
		/// 本期策略url
        /// </summary>
		[Column(DbType=@"VarChar(100)")]
		public string CUrl
		{
			get { return _CUrl; }
			set {
				if (_CUrl != value) {
					_CUrl = value;
				}
			}
		}
		
		private string _TabImgUrl;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"VarChar(100)")]
		public string TabImgUrl
		{
			get { return _TabImgUrl; }
			set {
				if (_TabImgUrl != value) {
					_TabImgUrl = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591