#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.NewsContent")]
	public partial class NewsContent 	{

		#region Construction
		public NewsContent()
		{
		}
		#endregion

		#region Column Mappings
		private int _NewsId;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int NOT NULL", IsPrimaryKey=true)]
		public int NewsId
		{
			get { return _NewsId; }
			set {
				if (_NewsId != value) {
					_NewsId = value;
				}
			}
		}
		
		private string _Content;
		/// <summary>
		/// 内容
        /// </summary>
		[Column(DbType=@"Text")]
		public string Content
		{
			get { return _Content; }
			set {
				if (_Content != value) {
					_Content = value;
				}
			}
		}
		
		private int? _ClickNum;
		/// <summary>
		/// 点击数统计
        /// </summary>
		[Column(DbType=@"Int")]
		public int? ClickNum
		{
			get { return _ClickNum; }
			set {
				if (_ClickNum != value) {
					_ClickNum = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591