#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.Permission")]
	public partial class Permission 	{

		#region Construction
		public Permission()
		{
		}
		#endregion

		#region Column Mappings
		private int _PermissionId;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int NOT NULL", IsPrimaryKey=true)]
		public int PermissionId
		{
			get { return _PermissionId; }
			set {
				if (_PermissionId != value) {
					_PermissionId = value;
				}
			}
		}
		
		private int _AdminId;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int NOT NULL", CanBeNull=false)]
		public int AdminId
		{
			get { return _AdminId; }
			set {
				if (_AdminId != value) {
					_AdminId = value;
				}
			}
		}
		
		private int _GroupId;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int NOT NULL", CanBeNull=false)]
		public int GroupId
		{
			get { return _GroupId; }
			set {
				if (_GroupId != value) {
					_GroupId = value;
				}
			}
		}
		
		private int _MenuId;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int NOT NULL", CanBeNull=false)]
		public int MenuId
		{
			get { return _MenuId; }
			set {
				if (_MenuId != value) {
					_MenuId = value;
				}
			}
		}
		
		private string _PermissionType;
		/// <summary>
		/// 权限类型，Single-个人权限，Group-组权限
        /// </summary>
		[Column(DbType=@"VarChar(10) NOT NULL", CanBeNull=false)]
		public string PermissionType
		{
			get { return _PermissionType; }
			set {
				if (_PermissionType != value) {
					_PermissionType = value;
				}
			}
		}
		
		private int _Status;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int NOT NULL", CanBeNull=false)]
		public int Status
		{
			get { return _Status; }
			set {
				if (_Status != value) {
					_Status = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591