#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.PopupMsgPlan")]
	public partial class PopupMsgPlan 	{

		#region Construction
		public PopupMsgPlan()
		{
		}
		#endregion

		#region Column Mappings
		private int _PlanId;
		/// <summary>
		/// 计划Id
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int PlanId
		{
			get { return _PlanId; }
			set {
				if (_PlanId != value) {
					_PlanId = value;
				}
			}
		}
		
		private string _Title;
		/// <summary>
		/// 标题
        /// </summary>
		[Column(DbType=@"NVarChar(30)")]
		public string Title
		{
			get { return _Title; }
			set {
				if (_Title != value) {
					_Title = value;
				}
			}
		}
		
		private string _Content;
		/// <summary>
		/// 内容
        /// </summary>
		[Column(DbType=@"NVarChar(1000)")]
		public string Content
		{
			get { return _Content; }
			set {
				if (_Content != value) {
					_Content = value;
				}
			}
		}
		
		private string _ImgUrl;
		/// <summary>
		/// 图片链接
        /// </summary>
		[Column(DbType=@"NVarChar(100)")]
		public string ImgUrl
		{
			get { return _ImgUrl; }
			set {
				if (_ImgUrl != value) {
					_ImgUrl = value;
				}
			}
		}
		
		private string _PageUrl;
		/// <summary>
		/// 页面链接
        /// </summary>
		[Column(DbType=@"VarChar(200)")]
		public string PageUrl
		{
			get { return _PageUrl; }
			set {
				if (_PageUrl != value) {
					_PageUrl = value;
				}
			}
		}
		
		private int? _PlanType;
		/// <summary>
		/// 发送计划类型  0：立刻，1：定时
        /// </summary>
		[Column(DbType=@"Int")]
		public int? PlanType
		{
			get { return _PlanType; }
			set {
				if (_PlanType != value) {
					_PlanType = value;
				}
			}
		}
		
		private int? _PopupType;
		/// <summary>
		/// 弹窗类型  0：中间弹窗，1：右下角弹窗
        /// </summary>
		[Column(DbType=@"Int")]
		public int? PopupType
		{
			get { return _PopupType; }
			set {
				if (_PopupType != value) {
					_PopupType = value;
				}
			}
		}
		
		private int? _Status;
		/// <summary>
		/// 计划状态  0：待发送，1：正在发送，2：发送完成，3：已取消发送，4：发送中被中止
        /// </summary>
		[Column(DbType=@"Int")]
		public int? Status
		{
			get { return _Status; }
			set {
				if (_Status != value) {
					_Status = value;
				}
			}
		}
		
		private int? _ReceiverType;
		/// <summary>
		/// 接收者类型  0：用户组，1：用户
        /// </summary>
		[Column(DbType=@"Int")]
		public int? ReceiverType
		{
			get { return _ReceiverType; }
			set {
				if (_ReceiverType != value) {
					_ReceiverType = value;
				}
			}
		}
		
		private string _Receiver;
		/// <summary>
		/// 接受者，多个值中间用“,” 隔开，当ReceiverType为0时，存储的是用户组的值，当ReceiverType为1时，存储的是用户名的值
        /// </summary>
		[Column(DbType=@"NVarChar(1000)")]
		public string Receiver
		{
			get { return _Receiver; }
			set {
				if (_Receiver != value) {
					_Receiver = value;
				}
			}
		}
		
		private DateTime? _CreatedTime;
		/// <summary>
		/// 创建时间
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? CreatedTime
		{
			get { return _CreatedTime; }
			set {
				if (_CreatedTime != value) {
					_CreatedTime = value;
				}
			}
		}
		
		private DateTime? _BeginTime;
		/// <summary>
		/// 消息开始发送时间
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? BeginTime
		{
			get { return _BeginTime; }
			set {
				if (_BeginTime != value) {
					_BeginTime = value;
				}
			}
		}
		
		private DateTime? _EndTime;
		/// <summary>
		/// 消息结束发送时间
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? EndTime
		{
			get { return _EndTime; }
			set {
				if (_EndTime != value) {
					_EndTime = value;
				}
			}
		}
		
		private int _ReceiverCount;
		/// <summary>
		/// 计划接收用户数
        /// </summary>
		[Column(DbType=@"Int NOT NULL", CanBeNull=false)]
		public int ReceiverCount
		{
			get { return _ReceiverCount; }
			set {
				if (_ReceiverCount != value) {
					_ReceiverCount = value;
				}
			}
		}
		
		private int _ViewCount;
		/// <summary>
		/// 实际接收用户数
        /// </summary>
		[Column(DbType=@"Int NOT NULL", CanBeNull=false)]
		public int ViewCount
		{
			get { return _ViewCount; }
			set {
				if (_ViewCount != value) {
					_ViewCount = value;
				}
			}
		}
		
		private int _ClickCount;
		/// <summary>
		/// 点击链接用户数
        /// </summary>
		[Column(DbType=@"Int NOT NULL", CanBeNull=false)]
		public int ClickCount
		{
			get { return _ClickCount; }
			set {
				if (_ClickCount != value) {
					_ClickCount = value;
				}
			}
		}
		
		private string _Editor;
		/// <summary>
		/// 操作人
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string Editor
		{
			get { return _Editor; }
			set {
				if (_Editor != value) {
					_Editor = value;
				}
			}
		}
		
		private string _PushVersion;
		/// <summary>
		/// 推送版本
        /// </summary>
		[Column(DbType=@"NVarChar(50)")]
		public string PushVersion
		{
			get { return _PushVersion; }
			set {
				if (_PushVersion != value) {
					_PushVersion = value;
				}
			}
		}
		
		private string _PushColumn;
		/// <summary>
		/// 推送栏目
        /// </summary>
		[Column(DbType=@"NVarChar(50)")]
		public string PushColumn
		{
			get { return _PushColumn; }
			set {
				if (_PushColumn != value) {
					_PushColumn = value;
				}
			}
		}
		
		private string _PushPlatform;
		/// <summary>
		/// 推送平台
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string PushPlatform
		{
			get { return _PushPlatform; }
			set {
				if (_PushPlatform != value) {
					_PushPlatform = value;
				}
			}
		}
		
		private string _DataType;
		/// <summary>
		/// 数据类型, 如: 广告弹窗, 资讯弹窗
        /// </summary>
		[Column(DbType=@"NVarChar(50)")]
		public string DataType
		{
			get { return _DataType; }
			set {
				if (_DataType != value) {
					_DataType = value;
				}
			}
		}
		
		private int? _NewsId;
		/// <summary>
		/// 新闻Id, 资讯Id
        /// </summary>
		[Column(DbType=@"Int")]
		public int? NewsId
		{
			get { return _NewsId; }
			set {
				if (_NewsId != value) {
					_NewsId = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591