#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.PopupMsgStatistics")]
	public partial class PopupMsgStatistics 	{

		#region Construction
		public PopupMsgStatistics()
		{
		}
		#endregion

		#region Column Mappings
		private int _Id;
		/// <summary>
		/// ID
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int Id
		{
			get { return _Id; }
			set {
				if (_Id != value) {
					_Id = value;
				}
			}
		}
		
		private int? _PlanId;
		/// <summary>
		/// 计划Id
        /// </summary>
		[Column(DbType=@"Int")]
		public int? PlanId
		{
			get { return _PlanId; }
			set {
				if (_PlanId != value) {
					_PlanId = value;
				}
			}
		}
		
		private string _CustomerName;
		/// <summary>
		/// 用户名
        /// </summary>
		[Column(DbType=@"NVarChar(100)")]
		public string CustomerName
		{
			get { return _CustomerName; }
			set {
				if (_CustomerName != value) {
					_CustomerName = value;
				}
			}
		}
		
		private DateTime? _CreatedTime;
		/// <summary>
		/// 时间
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? CreatedTime
		{
			get { return _CreatedTime; }
			set {
				if (_CreatedTime != value) {
					_CreatedTime = value;
				}
			}
		}
		
		private int? _PopupType;
		/// <summary>
		/// 类型：1.展示 2.统计
        /// </summary>
		[Column(DbType=@"Int")]
		public int? PopupType
		{
			get { return _PopupType; }
			set {
				if (_PopupType != value) {
					_PopupType = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591