#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.QuestionnairesAnswer")]
	public partial class QuestionnairesAnswer 	{

		#region Construction
		public QuestionnairesAnswer()
		{
		}
		#endregion

		#region Column Mappings
		private int _QaId;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int QaId
		{
			get { return _QaId; }
			set {
				if (_QaId != value) {
					_QaId = value;
				}
			}
		}
		
		private int? _QId;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int")]
		public int? QId
		{
			get { return _QId; }
			set {
				if (_QId != value) {
					_QId = value;
				}
			}
		}
		
		private int? _QoId;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int")]
		public int? QoId
		{
			get { return _QoId; }
			set {
				if (_QoId != value) {
					_QoId = value;
				}
			}
		}
		
		private string _Info;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"NVarChar(3000)")]
		public string Info
		{
			get { return _Info; }
			set {
				if (_Info != value) {
					_Info = value;
				}
			}
		}
		
		private int? _CustomerId;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int")]
		public int? CustomerId
		{
			get { return _CustomerId; }
			set {
				if (_CustomerId != value) {
					_CustomerId = value;
				}
			}
		}
		
		private string _UserName;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"NVarChar(50)")]
		public string UserName
		{
			get { return _UserName; }
			set {
				if (_UserName != value) {
					_UserName = value;
				}
			}
		}
		
		private DateTime? _CreateTime;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? CreateTime
		{
			get { return _CreateTime; }
			set {
				if (_CreateTime != value) {
					_CreateTime = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591