#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.ReceiveMsg")]
	public partial class ReceiveMsg 	{

		#region Construction
		public ReceiveMsg()
		{
		}
		#endregion

		#region Column Mappings
		private int _MsgId;
		/// <summary>
		/// ID
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int MsgId
		{
			get { return _MsgId; }
			set {
				if (_MsgId != value) {
					_MsgId = value;
				}
			}
		}
		
		private string _Title;
		/// <summary>
		/// 标题
        /// </summary>
		[Column(DbType=@"NVarChar(30)")]
		public string Title
		{
			get { return _Title; }
			set {
				if (_Title != value) {
					_Title = value;
				}
			}
		}
		
		private string _Content;
		/// <summary>
		/// 内容
        /// </summary>
		[Column(DbType=@"NVarChar(1000)")]
		public string Content
		{
			get { return _Content; }
			set {
				if (_Content != value) {
					_Content = value;
				}
			}
		}
		
		private string _ImgUrl;
		/// <summary>
		/// 图片链接
        /// </summary>
		[Column(DbType=@"NVarChar(100)")]
		public string ImgUrl
		{
			get { return _ImgUrl; }
			set {
				if (_ImgUrl != value) {
					_ImgUrl = value;
				}
			}
		}
		
		private string _PageUrl;
		/// <summary>
		/// 页面链接
        /// </summary>
		[Column(DbType=@"VarChar(200)")]
		public string PageUrl
		{
			get { return _PageUrl; }
			set {
				if (_PageUrl != value) {
					_PageUrl = value;
				}
			}
		}
		
		private int? _SenderId;
		/// <summary>
		/// 发送者Id
        /// </summary>
		[Column(DbType=@"Int")]
		public int? SenderId
		{
			get { return _SenderId; }
			set {
				if (_SenderId != value) {
					_SenderId = value;
				}
			}
		}
		
		private string _Sender;
		/// <summary>
		/// 发送者
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string Sender
		{
			get { return _Sender; }
			set {
				if (_Sender != value) {
					_Sender = value;
				}
			}
		}
		
		private int? _ReceiverId;
		/// <summary>
		/// 接收者Id
        /// </summary>
		[Column(DbType=@"Int")]
		public int? ReceiverId
		{
			get { return _ReceiverId; }
			set {
				if (_ReceiverId != value) {
					_ReceiverId = value;
				}
			}
		}
		
		private string _Receiver;
		/// <summary>
		/// 接收者
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string Receiver
		{
			get { return _Receiver; }
			set {
				if (_Receiver != value) {
					_Receiver = value;
				}
			}
		}
		
		private DateTime? _CreaedTime;
		/// <summary>
		/// 创建时间
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? CreaedTime
		{
			get { return _CreaedTime; }
			set {
				if (_CreaedTime != value) {
					_CreaedTime = value;
				}
			}
		}
		
		private DateTime? _SendTime;
		/// <summary>
		/// 发送时间
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? SendTime
		{
			get { return _SendTime; }
			set {
				if (_SendTime != value) {
					_SendTime = value;
				}
			}
		}
		
		private int? _MsgSource;
		/// <summary>
		/// 消息来源  1：软件弹窗，2：后台回复
        /// </summary>
		[Column(DbType=@"Int")]
		public int? MsgSource
		{
			get { return _MsgSource; }
			set {
				if (_MsgSource != value) {
					_MsgSource = value;
				}
			}
		}
		
		private int? _MsgSourceId;
		/// <summary>
		/// (PopupMsgPlan)原始表Id
        /// </summary>
		[Column(DbType=@"Int")]
		public int? MsgSourceId
		{
			get { return _MsgSourceId; }
			set {
				if (_MsgSourceId != value) {
					_MsgSourceId = value;
				}
			}
		}
		
		private string _ReplyQuestion;
		/// <summary>
		/// 回复问题，只有当MsgSource=2时，才存储此项
        /// </summary>
		[Column(DbType=@"NVarChar(600)")]
		public string ReplyQuestion
		{
			get { return _ReplyQuestion; }
			set {
				if (_ReplyQuestion != value) {
					_ReplyQuestion = value;
				}
			}
		}
		
		private int? _Status;
		/// <summary>
		/// 状态   0：不可用，1：可用
        /// </summary>
		[Column(DbType=@"Int")]
		public int? Status
		{
			get { return _Status; }
			set {
				if (_Status != value) {
					_Status = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591