#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.Reptile")]
	public partial class Reptile 	{

		#region Construction
		public Reptile()
		{
		}
		#endregion

		#region Column Mappings
		private int _ReptileId;
		/// <summary>
		/// 爬虫Id
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int ReptileId
		{
			get { return _ReptileId; }
			set {
				if (_ReptileId != value) {
					_ReptileId = value;
				}
			}
		}
		
		private string _ReptileTitle;
		/// <summary>
		/// 爬虫标题
        /// </summary>
		[Column(DbType=@"VarChar(200)")]
		public string ReptileTitle
		{
			get { return _ReptileTitle; }
			set {
				if (_ReptileTitle != value) {
					_ReptileTitle = value;
				}
			}
		}
		
		private string _ReptileContent;
		/// <summary>
		/// 爬虫内容
        /// </summary>
		[Column(DbType=@"NVarChar(MAX)")]
		public string ReptileContent
		{
			get { return _ReptileContent; }
			set {
				if (_ReptileContent != value) {
					_ReptileContent = value;
				}
			}
		}
		
		private string _ReptileUrl;
		/// <summary>
		/// 爬虫路径
        /// </summary>
		[Column(DbType=@"NVarChar(MAX)")]
		public string ReptileUrl
		{
			get { return _ReptileUrl; }
			set {
				if (_ReptileUrl != value) {
					_ReptileUrl = value;
				}
			}
		}
		
		private string _ReptileFrom;
		/// <summary>
		/// 爬虫来源
        /// </summary>
		[Column(DbType=@"VarChar(100)")]
		public string ReptileFrom
		{
			get { return _ReptileFrom; }
			set {
				if (_ReptileFrom != value) {
					_ReptileFrom = value;
				}
			}
		}
		
		private string _CreateUser;
		/// <summary>
		/// 创建人
        /// </summary>
		[Column(DbType=@"VarChar(50)")]
		public string CreateUser
		{
			get { return _CreateUser; }
			set {
				if (_CreateUser != value) {
					_CreateUser = value;
				}
			}
		}
		
		private DateTime? _CreateTime;
		/// <summary>
		/// 创建时间
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? CreateTime
		{
			get { return _CreateTime; }
			set {
				if (_CreateTime != value) {
					_CreateTime = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591