#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.SendMsg")]
	public partial class SendMsg 	{

		#region Construction
		public SendMsg()
		{
		}
		#endregion

		#region Column Mappings
		private int _MsgId;
		/// <summary>
		/// 消息ID
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int MsgId
		{
			get { return _MsgId; }
			set {
				if (_MsgId != value) {
					_MsgId = value;
				}
			}
		}
		
		private int? _MsgTypeId;
		/// <summary>
		/// 提问类型
        /// </summary>
		[Column(DbType=@"Int")]
		public int? MsgTypeId
		{
			get { return _MsgTypeId; }
			set {
				if (_MsgTypeId != value) {
					_MsgTypeId = value;
				}
			}
		}
		
		private string _MsgContent;
		/// <summary>
		/// 提问内容
        /// </summary>
		[Column(DbType=@"NVarChar(600)")]
		public string MsgContent
		{
			get { return _MsgContent; }
			set {
				if (_MsgContent != value) {
					_MsgContent = value;
				}
			}
		}
		
		private int? _QuCustomerId;
		/// <summary>
		/// 提问人id
        /// </summary>
		[Column(DbType=@"Int")]
		public int? QuCustomerId
		{
			get { return _QuCustomerId; }
			set {
				if (_QuCustomerId != value) {
					_QuCustomerId = value;
				}
			}
		}
		
		private string _QuCustomerName;
		/// <summary>
		/// 提问人
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string QuCustomerName
		{
			get { return _QuCustomerName; }
			set {
				if (_QuCustomerName != value) {
					_QuCustomerName = value;
				}
			}
		}
		
		private DateTime? _QuTime;
		/// <summary>
		/// 提问时间
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? QuTime
		{
			get { return _QuTime; }
			set {
				if (_QuTime != value) {
					_QuTime = value;
				}
			}
		}
		
		private string _ReplyContent;
		/// <summary>
		/// 回复内容
        /// </summary>
		[Column(DbType=@"NVarChar(600)")]
		public string ReplyContent
		{
			get { return _ReplyContent; }
			set {
				if (_ReplyContent != value) {
					_ReplyContent = value;
				}
			}
		}
		
		private DateTime? _ReplyTime;
		/// <summary>
		/// 回复时间
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? ReplyTime
		{
			get { return _ReplyTime; }
			set {
				if (_ReplyTime != value) {
					_ReplyTime = value;
				}
			}
		}
		
		private string _Replier;
		/// <summary>
		/// 回复人
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string Replier
		{
			get { return _Replier; }
			set {
				if (_Replier != value) {
					_Replier = value;
				}
			}
		}
		
		private string _Editor;
		/// <summary>
		/// 操作人
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string Editor
		{
			get { return _Editor; }
			set {
				if (_Editor != value) {
					_Editor = value;
				}
			}
		}
		
		private string _PhoneOrEmail;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"NVarChar(80)")]
		public string PhoneOrEmail
		{
			get { return _PhoneOrEmail; }
			set {
				if (_PhoneOrEmail != value) {
					_PhoneOrEmail = value;
				}
			}
		}
		
		private string _ImgUrl;
		/// <summary>
		/// 上传图片的路径
        /// </summary>
		[Column(DbType=@"NVarChar(50)")]
		public string ImgUrl
		{
			get { return _ImgUrl; }
			set {
				if (_ImgUrl != value) {
					_ImgUrl = value;
				}
			}
		}
		
		private string _Tel;
		/// <summary>
		/// 电话号码
        /// </summary>
		[Column(DbType=@"VarChar(20)")]
		public string Tel
		{
			get { return _Tel; }
			set {
				if (_Tel != value) {
					_Tel = value;
				}
			}
		}
		
		private string _SoftwareVersion;
		/// <summary>
		/// 软件版本：严林版、金牡丹版、渤海版、百川财富版、金蝴蝶版
        /// </summary>
		[Column(DbType=@"VarChar(20)")]
		public string SoftwareVersion
		{
			get { return _SoftwareVersion; }
			set {
				if (_SoftwareVersion != value) {
					_SoftwareVersion = value;
				}
			}
		}
		
		private string _HardwareVersion;
		/// <summary>
		/// 硬件版本：PC 、Ios、Android
        /// </summary>
		[Column(DbType=@"VarChar(20)")]
		public string HardwareVersion
		{
			get { return _HardwareVersion; }
			set {
				if (_HardwareVersion != value) {
					_HardwareVersion = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591