#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.sqlResult_733652$")]
	public partial class SqlResult_733652_ 	{

		#region Construction
		public SqlResult_733652_()
		{
		}
		#endregion

		#region Column Mappings
		private double? _ID;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Float")]
		public double? ID
		{
			get { return _ID; }
			set {
				if (_ID != value) {
					_ID = value;
				}
			}
		}
		
		private string _Name;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"NVarChar(255)")]
		public string Name
		{
			get { return _Name; }
			set {
				if (_Name != value) {
					_Name = value;
				}
			}
		}
		
		private string _Nick;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"NVarChar(255)")]
		public string Nick
		{
			get { return _Nick; }
			set {
				if (_Nick != value) {
					_Nick = value;
				}
			}
		}
		
		private double? _Sex;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Float")]
		public double? Sex
		{
			get { return _Sex; }
			set {
				if (_Sex != value) {
					_Sex = value;
				}
			}
		}
		
		private string _Info;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"NVarChar(255)")]
		public string Info
		{
			get { return _Info; }
			set {
				if (_Info != value) {
					_Info = value;
				}
			}
		}
		
		private string _Personality;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"NVarChar(255)")]
		public string Personality
		{
			get { return _Personality; }
			set {
				if (_Personality != value) {
					_Personality = value;
				}
			}
		}
		
		private double? _Section;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Float")]
		public double? Section
		{
			get { return _Section; }
			set {
				if (_Section != value) {
					_Section = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591