#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.SSOResult")]
	public partial class SSOResult 	{

		#region Construction
		public SSOResult()
		{
		}
		#endregion

		#region Column Mappings
		private int _Id;
		/// <summary>
		/// ID
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int Id
		{
			get { return _Id; }
			set {
				if (_Id != value) {
					_Id = value;
				}
			}
		}
		
		private int? _PlanId;
		/// <summary>
		/// 计划Id
        /// </summary>
		[Column(DbType=@"Int")]
		public int? PlanId
		{
			get { return _PlanId; }
			set {
				if (_PlanId != value) {
					_PlanId = value;
				}
			}
		}
		
		private string _Url;
		/// <summary>
		/// 弹窗链接
        /// </summary>
		[Column(DbType=@"VarChar(200)")]
		public string Url
		{
			get { return _Url; }
			set {
				if (_Url != value) {
					_Url = value;
				}
			}
		}
		
		private string _SuccessUser;
		/// <summary>
		/// 成功的用户
        /// </summary>
		[Column(DbType=@"Text")]
		public string SuccessUser
		{
			get { return _SuccessUser; }
			set {
				if (_SuccessUser != value) {
					_SuccessUser = value;
				}
			}
		}
		
		private string _ErrorUser;
		/// <summary>
		/// 出错的用户
        /// </summary>
		[Column(DbType=@"Text")]
		public string ErrorUser
		{
			get { return _ErrorUser; }
			set {
				if (_ErrorUser != value) {
					_ErrorUser = value;
				}
			}
		}
		
		private string _RepeatUser;
		/// <summary>
		/// 重复的用户
        /// </summary>
		[Column(DbType=@"Text")]
		public string RepeatUser
		{
			get { return _RepeatUser; }
			set {
				if (_RepeatUser != value) {
					_RepeatUser = value;
				}
			}
		}
		
		private string _UndefinedUser;
		/// <summary>
		/// 不存在用户
        /// </summary>
		[Column(DbType=@"Text")]
		public string UndefinedUser
		{
			get { return _UndefinedUser; }
			set {
				if (_UndefinedUser != value) {
					_UndefinedUser = value;
				}
			}
		}
		
		private DateTime? _BeginTime;
		/// <summary>
		/// 消息开始发送时间
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? BeginTime
		{
			get { return _BeginTime; }
			set {
				if (_BeginTime != value) {
					_BeginTime = value;
				}
			}
		}
		
		private DateTime? _EndTime;
		/// <summary>
		/// 消息结束发送时间
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? EndTime
		{
			get { return _EndTime; }
			set {
				if (_EndTime != value) {
					_EndTime = value;
				}
			}
		}
		
		private int? _PopupType;
		/// <summary>
		/// 弹窗类型，0：中间弹窗，1：右下角弹窗
        /// </summary>
		[Column(DbType=@"Int")]
		public int? PopupType
		{
			get { return _PopupType; }
			set {
				if (_PopupType != value) {
					_PopupType = value;
				}
			}
		}
		
		private int? _Status;
		/// <summary>
		/// 调用接口状态码，0：成功，1：该消息id 已存在，2：链接地址不存在，3：用户群组不存在，4：开始时间与结束时间不匹配，9：其它异常
        /// </summary>
		[Column(DbType=@"Int")]
		public int? Status
		{
			get { return _Status; }
			set {
				if (_Status != value) {
					_Status = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591