#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.StockNameInfo")]
	public partial class StockNameInfo 	{

		#region Construction
		public StockNameInfo()
		{
		}
		#endregion

		#region Column Mappings
		private int _Id;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int Id
		{
			get { return _Id; }
			set {
				if (_Id != value) {
					_Id = value;
				}
			}
		}
		
		private string _StockCode;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"NVarChar(10)")]
		public string StockCode
		{
			get { return _StockCode; }
			set {
				if (_StockCode != value) {
					_StockCode = value;
				}
			}
		}
		
		private string _StockName;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"NVarChar(50)")]
		public string StockName
		{
			get { return _StockName; }
			set {
				if (_StockName != value) {
					_StockName = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591