#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.TemplateDetail")]
	public partial class TemplateDetail 	{

		#region Construction
		public TemplateDetail()
		{
		}
		#endregion

		#region Column Mappings
		private int _DetailId;
		/// <summary>
		/// 明细ID
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int DetailId
		{
			get { return _DetailId; }
			set {
				if (_DetailId != value) {
					_DetailId = value;
				}
			}
		}
		
		private int? _TemplateId;
		/// <summary>
		/// 模板ID
        /// </summary>
		[Column(DbType=@"Int")]
		public int? TemplateId
		{
			get { return _TemplateId; }
			set {
				if (_TemplateId != value) {
					_TemplateId = value;
				}
			}
		}
		
		private string _ChannelId;
		/// <summary>
		/// 栏目ID
        /// </summary>
		[Column(DbType=@"VarChar(20)")]
		public string ChannelId
		{
			get { return _ChannelId; }
			set {
				if (_ChannelId != value) {
					_ChannelId = value;
				}
			}
		}
		
		private int? _RelationType;
		/// <summary>
		/// 1:涉及；2:所属
        /// </summary>
		[Column(DbType=@"Int")]
		public int? RelationType
		{
			get { return _RelationType; }
			set {
				if (_RelationType != value) {
					_RelationType = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591