#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.Topic")]
	public partial class Topic 	{

		#region Construction
		public Topic()
		{
		}
		#endregion

		#region Column Mappings
		private int _TopicId;
		/// <summary>
		/// 专题Id
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int TopicId
		{
			get { return _TopicId; }
			set {
				if (_TopicId != value) {
					_TopicId = value;
				}
			}
		}
		
		private string _TopicName;
		/// <summary>
		/// 专题名称
        /// </summary>
		[Column(DbType=@"NVarChar(50)")]
		public string TopicName
		{
			get { return _TopicName; }
			set {
				if (_TopicName != value) {
					_TopicName = value;
				}
			}
		}
		
		private int? _TopicTypeId;
		/// <summary>
		/// 专题类型Id
        /// </summary>
		[Column(DbType=@"Int")]
		public int? TopicTypeId
		{
			get { return _TopicTypeId; }
			set {
				if (_TopicTypeId != value) {
					_TopicTypeId = value;
				}
			}
		}
		
		private string _Status;
		/// <summary>
		/// 状态: 已发布, 未发布
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string Status
		{
			get { return _Status; }
			set {
				if (_Status != value) {
					_Status = value;
				}
			}
		}
		
		private string _Remark;
		/// <summary>
		/// 备注
        /// </summary>
		[Column(DbType=@"NVarChar(500)")]
		public string Remark
		{
			get { return _Remark; }
			set {
				if (_Remark != value) {
					_Remark = value;
				}
			}
		}
		
		private string _CreatedUser;
		/// <summary>
		/// 创建用户
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string CreatedUser
		{
			get { return _CreatedUser; }
			set {
				if (_CreatedUser != value) {
					_CreatedUser = value;
				}
			}
		}
		
		private DateTime? _CreatedTime;
		/// <summary>
		/// 创建时间
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? CreatedTime
		{
			get { return _CreatedTime; }
			set {
				if (_CreatedTime != value) {
					_CreatedTime = value;
				}
			}
		}
		
		private DateTime? _PublishTime;
		/// <summary>
		/// 发布时间
        /// </summary>
		[Column(DbType=@"DateTime")]
		public DateTime? PublishTime
		{
			get { return _PublishTime; }
			set {
				if (_PublishTime != value) {
					_PublishTime = value;
				}
			}
		}
		
		private int? _IsTop;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"Int")]
		public int? IsTop
		{
			get { return _IsTop; }
			set {
				if (_IsTop != value) {
					_IsTop = value;
				}
			}
		}
		
		private string _ImgUrl;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"NVarChar(100)")]
		public string ImgUrl
		{
			get { return _ImgUrl; }
			set {
				if (_ImgUrl != value) {
					_ImgUrl = value;
				}
			}
		}
		
		private string _FileUrl;
		/// <summary>
		/// 
        /// </summary>
		[Column(DbType=@"NVarChar(100)")]
		public string FileUrl
		{
			get { return _FileUrl; }
			set {
				if (_FileUrl != value) {
					_FileUrl = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591