#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.TopicType")]
	public partial class TopicType 	{

		#region Construction
		public TopicType()
		{
		}
		#endregion

		#region Column Mappings
		private int _TopicTypeId;
		/// <summary>
		/// 专题类型Id
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int TopicTypeId
		{
			get { return _TopicTypeId; }
			set {
				if (_TopicTypeId != value) {
					_TopicTypeId = value;
				}
			}
		}
		
		private string _TopicTypeName;
		/// <summary>
		/// 专题类型名称
        /// </summary>
		[Column(DbType=@"NVarChar(50)")]
		public string TopicTypeName
		{
			get { return _TopicTypeName; }
			set {
				if (_TopicTypeName != value) {
					_TopicTypeName = value;
				}
			}
		}
		
		private string _TopicTypeGenerate;
		/// <summary>
		/// 专题生成类型: 最新, 每日, 每周, 每月
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string TopicTypeGenerate
		{
			get { return _TopicTypeGenerate; }
			set {
				if (_TopicTypeGenerate != value) {
					_TopicTypeGenerate = value;
				}
			}
		}
		
		private int? _TemplateId;
		/// <summary>
		/// 模版Id
        /// </summary>
		[Column(DbType=@"Int")]
		public int? TemplateId
		{
			get { return _TemplateId; }
			set {
				if (_TemplateId != value) {
					_TemplateId = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591