#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using Common;
using System.Data.Linq;
using System.ComponentModel;

namespace CMS.Model
{	
	[Table(Name=@"dbo.TransStatistics")]
	public partial class TransStatistics 	{

		#region Construction
		public TransStatistics()
		{
		}
		#endregion

		#region Column Mappings
		private int _Id;
		/// <summary>
		/// ID
        /// </summary>
		[Column(DbType=@"Int NOT NULL IDENTITY", IsPrimaryKey=true)]
		public int Id
		{
			get { return _Id; }
			set {
				if (_Id != value) {
					_Id = value;
				}
			}
		}
		
		private int? _AnalystId;
		/// <summary>
		/// 分析师Id
        /// </summary>
		[Column(DbType=@"Int")]
		public int? AnalystId
		{
			get { return _AnalystId; }
			set {
				if (_AnalystId != value) {
					_AnalystId = value;
				}
			}
		}
		
		private string _AnalystName;
		/// <summary>
		/// 分析师名称
        /// </summary>
		[Column(DbType=@"NVarChar(20)")]
		public string AnalystName
		{
			get { return _AnalystName; }
			set {
				if (_AnalystName != value) {
					_AnalystName = value;
				}
			}
		}
		
		private int? _MarkupBuyNum;
		/// <summary>
		/// 多开
        /// </summary>
		[Column(DbType=@"Int")]
		public int? MarkupBuyNum
		{
			get { return _MarkupBuyNum; }
			set {
				if (_MarkupBuyNum != value) {
					_MarkupBuyNum = value;
				}
			}
		}
		
		private int? _FallBuyNum;
		/// <summary>
		/// 空开
        /// </summary>
		[Column(DbType=@"Int")]
		public int? FallBuyNum
		{
			get { return _FallBuyNum; }
			set {
				if (_FallBuyNum != value) {
					_FallBuyNum = value;
				}
			}
		}
		
		private int? _ProfitNum;
		/// <summary>
		/// 盈利次数
        /// </summary>
		[Column(DbType=@"Int")]
		public int? ProfitNum
		{
			get { return _ProfitNum; }
			set {
				if (_ProfitNum != value) {
					_ProfitNum = value;
				}
			}
		}
		
		private int? _LossNum;
		/// <summary>
		/// 亏损次数
        /// </summary>
		[Column(DbType=@"Int")]
		public int? LossNum
		{
			get { return _LossNum; }
			set {
				if (_LossNum != value) {
					_LossNum = value;
				}
			}
		}
		
		private decimal? _SuccessRate;
		/// <summary>
		/// 成功率
        /// </summary>
		[Column(DbType=@"Decimal(18,2)")]
		public decimal? SuccessRate
		{
			get { return _SuccessRate; }
			set {
				if (_SuccessRate != value) {
					_SuccessRate = value;
				}
			}
		}
		
		private int? _SType;
		/// <summary>
		/// 1月统计，2总统计
        /// </summary>
		[Column(DbType=@"Int")]
		public int? SType
		{
			get { return _SType; }
			set {
				if (_SType != value) {
					_SType = value;
				}
			}
		}
		
		#endregion
	}
}
#pragma warning restore 1591