#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by LINQ to SQL template for T4 C#
//     Modified by ZEN 6/7/2010 removed LINQ to SQL feathers.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using System.Data.Linq;
using Common;
using CMS.Model;

namespace CMS.DAL
{	
	public partial class NewsPopupDAL : BaseDAL<NewsPopup> 	{

		#region Construction
		public NewsPopupDAL()
		{
		}
		#endregion

	}
}
#pragma warning restore 1591